# Janus — an engine for building specialized AI agents.
# Copyright (C) 2026 Pantheos Forge
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version. This program is distributed WITHOUT ANY WARRANTY;
# see the GNU AGPL <https://www.gnu.org/licenses/> for details.
#
# A persona exception applies — see LICENSE-EXCEPTION.

"""Assemble a self-contained, vendored agent repo from a Persona.

``export_agent`` produces a directory that can be zipped up and handed to
someone else (or deployed as-is): it contains a wholesale copy of the
``janus`` package, the persona's own directory, and a set of small wrapper
files (rendered by ``janus.factory.render``) that turn the pair into a
runnable, installable project.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

import janus
from janus.factory.render import (
    render_agent_runner,
    render_compose,
    render_dockerfile,
    render_env_example,
    render_gitignore,
    render_pyproject,
    render_readme,
    render_smoke_test,
)

if TYPE_CHECKING:
    from janus.core.persona import Persona

_IGNORE_CACHES = shutil.ignore_patterns("__pycache__", "*.pyc")


def write_runtime_and_wrappers(persona: Persona, dest: str | Path, name: str) -> None:
    """Stamp the vendored ``janus/`` package and rendered wrapper files into ``dest``.

    ``dest/janus`` is removed and re-copied so files deleted upstream do not
    linger. The wrapper files are a fixed set and are always overwritten. The
    persona directory and ``.env`` are never touched here — ``export_agent``
    copies the persona itself; ``fleet sync`` preserves the existing one.
    """
    dest = Path(dest)
    janus_src = Path(janus.__file__).parent
    janus_dest = dest / "janus"
    if janus_dest.exists():
        shutil.rmtree(janus_dest)
    shutil.copytree(janus_src, janus_dest, ignore=_IGNORE_CACHES)

    (dest / "pyproject.toml").write_text(render_pyproject(name))
    (dest / "agent.py").write_text(render_agent_runner())
    (dest / "README.md").write_text(render_readme(persona, name))
    (dest / "Dockerfile").write_text(render_dockerfile(persona.container))
    if persona.container is not None:
        (dest / "docker-compose.yml").write_text(render_compose(name))
    (dest / ".env.example").write_text(render_env_example())
    (dest / ".gitignore").write_text(render_gitignore())
    (dest / "tests").mkdir(exist_ok=True)
    (dest / "tests" / "test_smoke.py").write_text(render_smoke_test())


def export_agent(
    persona: Persona,
    dest: str | Path,
    *,
    agent_name: str | None = None,
    git_init: bool = True,
    force: bool = False,
) -> Path:
    """Stamp out a self-contained vendored agent repo at ``dest``.

    Copies the ``janus`` package and the persona's directory wholesale, writes
    the rendered wrapper files (pyproject, agent.py, README, Dockerfile, env
    example, gitignore, smoke test), and optionally initializes a git repo
    with an initial commit. Returns ``dest``.

    If ``dest`` exists and is not empty, raises ``FileExistsError`` unless
    ``force=True``, in which case the destination is wiped and re-exported.
    """
    name = agent_name or persona.name
    dest = Path(dest)
    if dest.exists() and any(dest.iterdir()):
        if not force:
            raise FileExistsError(
                f"export destination {dest} already exists and is not empty; "
                "pass force=True (or --force) to replace it"
            )
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)

    shutil.copytree(persona.directory, dest / "persona", ignore=_IGNORE_CACHES, dirs_exist_ok=True)
    write_runtime_and_wrappers(persona, dest, name)

    if git_init:
        try:
            subprocess.run(["git", "init", "-q"], cwd=dest, check=True)
            subprocess.run(["git", "add", "-A"], cwd=dest, check=True)
            subprocess.run(
                [
                    "git",
                    "-c",
                    "user.email=agent@janus.local",
                    "-c",
                    "user.name=Janus",
                    "commit",
                    "-q",
                    "-m",
                    f"Initial commit: {name} (generated by Janus)",
                ],
                cwd=dest,
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(f"git initialization failed for exported agent at {dest}") from exc

    return dest
